### ISSUE TITLE
Issue of lazy evaluation with dev magrittr

### ISSUE THREAD

**Issue by lionel-** [restonslacker/taber#4]
Hello, I'm seeing an issue with the development version of magrittr which switches to a lazy evaluation approach. It causes this error in your package:

```r
> aframe <- data.frame(zed = runif(100))
> set_to_zero <- . %>% mutate(zed = 0)
> aframe %>% scion(zed >0.5, false_fun=set_to_zero) %>% mutate(zed=1) %>% graft
Error in .pop() : 
  No more scions on stack. Perhaps you meant to specify the "data2" argument to graft()?
Calls: %>% -> graft -> .pop
```

That's because the pipeline is now evaluated as if it were nested, instead of linearly:

```r
graft(mutate(scion(aframe, zed > 0.5, false_fun = set_to_zero), zed = 1))
```

Because of lazy evaluation, the input to `graft` has not been evaluated yet when you check if `data2` is missing. One way to fix this is to `force()` the input like this:

```diff
--- a/R/tabe.R
+++ b/R/tabe.R
@@ -62,6 +62,7 @@ scion <- function(.data, ..., false_fun, false_name, false_env){
 #' @importFrom dplyr intersect
 #' @importFrom dplyr full_join
 graft <- function(.data, combine_fun, data2){
+  force(.data)
   if(missing(data2))
     data2 <- .pop()
```

We're planning to release magrittr in one month. It'd be great if you could update your package :)

Note that the future native pipe in the next version of R will use this same approach, so by fixing your package for the new magrittr behaviour you'll make it usable with the native pipe as well.

**Comment by restonslacker** [comment]
Thank you for the report and the suggested fix. I will work on this week. it's been quite a while since i've worked on this package so i suspect it will need some other updates to remain in compliance with CRAN.

**Comment by restonslacker** [comment]
package submitted to CRAN. awaiting response.

**Comment by restonslacker** [comment]
accepted on cran

**Comment by lionel-** [comment]
Thanks!
